apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache-node 
spec:
  serviceName: "cache-service" 
  replicas: 3 
  selector:
    matchLabels:
      app: cache 
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache-container
        image: my-cache-image:local 
        imagePullPolicy: Never 
        command: ["python", "server.py"]
        args: ["$(POD_NAME).cache-service:50051"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 8080
          name: http-health
        

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080 
          initialDelaySeconds: 5 
          periodSeconds: 10 
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5